CER3/CER3/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views

urlpatterns = [
    path('', views.home, name="home"),
    path('login/', views.iniciarSesion, name="login"),
    path('logout/', views.cerrarSesion, name="logout"),
    path('admin/', admin.site.urls),
    path('rest/', include('rest.urls')), 
]

CER3/rest/urls.py
from rest_framework import routers
from .views import EventoViewSet
from django.urls import path, include 

router = routers.DefaultRouter()
router.register(r'evento', EventoViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

CER3/core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Segmento(models.Model):
    id = models.BigAutoField(primary_key=True)
    nombre = models.CharField(max_length=50)
    def __str__(self) -> str:
        return self.nombre

class Evento(models.Model):
    TIPO_CHOICES = [
        ("VA","Vacaciones"),
        ("FE","Feriado"),
        ("SS", "Suspensión de actividades"),
        ("SP", "Suspensión de actividades PM"),
        ("PL", "Periodo Lectivo"),
        ("SE", "Suspensión de evaluaciones"),
        ("CE", "Ceremonia"),
        ("ED", "EDDA"),
        ("EV", "Evaluación"),
        ("AY", "Ayudantías"),
        ("HA", "Hito Académico"),
        ("SA", "Secretaría Académica"),
        ("OA", "OAI"),
    ]
    id = models.BigAutoField(primary_key=True)
    fechaInicio = models.DateTimeField(auto_now_add=False)
    fechaTermino = models.DateTimeField(auto_now_add=False)
    titulo = models.CharField(max_length=100)
    descripcion = models.TextField()
    tipo = models.CharField(max_length=2, choices=TIPO_CHOICES)
    segmento = models.ManyToManyField(Segmento)

    def __str__(self) -> str:
        return self.titulo

class TipoUsuario(AbstractUser):
    tipo_cuenta = models.ForeignKey(Segmento, on_delete=models.CASCADE, null=True)

CER3/rest/models.py
from django.db import models

# Create your models here.

CER3/core/views.py
from django.shortcuts import render, redirect
from .models import Evento, Segmento
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.utils import timezone

def home(request):
    title = "Home"
    segmentos = Segmento.objects.all()
    segmento_seleccionado = request.GET.get("segmento")
    tipos = Evento.TIPO_CHOICES
    tipo_seleccionado = request.GET.get("tipo")
    segmento_usuario = None
    username = 'Anónimo'
    eventos_segmento = None
    fecha_usuario = timezone.now()
    segmento_dev = None
    if request.user.is_authenticated:
        if (str(request.user.tipo_cuenta)== 'Developer'):
            segmento_dev = request.user.tipo_cuenta
        username = request.user.username
        if (str(request.user.tipo_cuenta)== 'Jefe de Carrera' or str(request.user.tipo_cuenta) == 'Profesor'):
            segmento_usuario = request.user.tipo_cuenta
            eventos_segmento = Evento.objects.filter(segmento=segmento_usuario, fechaInicio__gte=timezone.now()).order_by('fechaInicio')[:3]

    if (segmento_seleccionado == 'Todos' or segmento_seleccionado is None) and (tipo_seleccionado == 'Todos' or tipo_seleccionado is None):
        eventos = Evento.objects.filter(fechaInicio__gte=timezone.now()).order_by('fechaInicio')
    else:
        if segmento_seleccionado == 'Todos' or segmento_seleccionado is None:
            for tipo in tipos:
                if str(tipo[0]) == str(tipo_seleccionado):
                    eventos = Evento.objects.filter(tipo=tipo[0], fechaInicio__gte=timezone.now()).order_by('fechaInicio')
                    break
        
        elif tipo_seleccionado == 'Todos' or tipo_seleccionado is None:
            segmento_a_filtrar = Segmento.objects.get(nombre=segmento_seleccionado)
            eventos = Evento.objects.filter(segmento=segmento_a_filtrar, fechaInicio__gte=timezone.now()).order_by('fechaInicio')

        else:
            segmento_a_filtrar = Segmento.objects.get(nombre=segmento_seleccionado)
            for tipo in tipos:
                if tipo[0] == tipo_seleccionado:
                    eventos = Evento.objects.filter(segmento=segmento_a_filtrar, tipo=tipo[0], fechaInicio__gte=timezone.now()).order_by('fechaInicio')
                    break
            
    data = {
        "title": title,
        "eventos": eventos,
        "segmentos" :segmentos,
        "tipos": tipos,
        "segmento_seleccionado": segmento_seleccionado,
        "tipo_seleccionado": tipo_seleccionado,
        "segmento_usuario": segmento_usuario,
        "username": username,
        "eventos_segmento": eventos_segmento,
        "fecha_usuario": fecha_usuario,
        'segmento_dev': segmento_dev
    }
    return render(request, 'core/home.html', data)

def cerrarSesion(request):
    logout(request)
    return redirect('home')

def iniciarSesion(request):
    if request.method == 'GET':
        data = {
            'form': AuthenticationForm
        }
        return render(request, 'core/login.html', data)
    else:
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            data = {
                'form': AuthenticationForm,
                'error': 'Usuario o contraseña incorrecta'
            }
            return render(request, 'core/login.html', data)
        else:
            login(request, user)
            return redirect('home')

CER3/rest/views.py
from rest_framework import viewsets
from .permissions import IsDeveloper
from core.models import Evento
from .serializers import EventoSerializer
from rest_framework.filters import SearchFilter
from core.models import Evento
from .serializers import EventoSerializer

class EventoViewSet(viewsets.ModelViewSet):
    queryset = Evento.objects.all()
    serializer_class = EventoSerializer
    permission_classes = [IsDeveloper]
    filter_backends = [SearchFilter]
    search_fields = ['fechaInicio' ,'segmento__nombre', 'tipo']

CER3/core/templates/core/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Eventos USM</title>
    <link rel="shortcut icon" href="{% static 'core/img/Logo_UTFSM.png' %}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href='https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'core/css/styles.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&family=Raleway:wght@200;300;400&family=Roboto+Condensed:wght@300&family=Staatliches&display=swap" rel="stylesheet">
  
    <script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.9/index.global.min.js'></script>
    <script src="{% static 'core/js/script.js' %}"></script>

  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <nav class="navbar navbar-expand-lg" style="background: #004B85;">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'home' %}">
                <img src="{% static 'core/img/Logo_UTFSM.png' %}" class="img-fluid" style="max-height: 60px;" alt="">
              </a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                  <a class="nav-link text-white" aria-current="page" href="{% url 'home' %}">Home</a>
                  {% if user.is_authenticated %}
                    {% if user.is_superuser %}
                      <a class="nav-link text-white" href="{% url 'admin:index' %}" target="_blank">Administración</a>
                    {% elif segmento_dev != None %}
                      <a class="nav-link text-white" href="/rest/evento/" target="_blank">Gestión Eventos</a>
                    {% endif %} 
                    <a class="nav-link text-white" href="logout">Logout, {{username}}</a>
                  {% else %}
                    <a class="nav-link text-white" href="{% url 'login' %}">Login</a>
                  {% endif %}
                </div>
              </div>
            </div>
          </nav>
      </div>
        
        {% block content %}

        {% endblock %}
    </div>
    <footer style="height: 20vh; width: 100%; background: #004B85;">
      <div class="d-flex align-items-center flex-column mb-3 p-5 text-white">
          <p id="dev">Desarrollado por <a class="text-white" href="https://github.com/etha44a4n/CER3-GRUPO11" target="_blank">Grupo 11</a></p>
      </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

CER3/core/templates/core/calendario.html
{% load static %}

<div class="row"style="background: #005f94;">
    <div class="card border-0 d-none d-md-block text-center p-5" style="max-height: 90vh; width: 100%; background: #005f94;">
      <div class="card-overlay">
        <h1 class="card-title text-white">Calendario de Actividades</h1>
        <div class="object-fit-contain">
          <div id='calendar' style="max-height: 60vh;" class="text-white"></div>
        </div>
      </div>
    </div>
</div>
    

    

CER3/core/templates/core/home.html
{% extends 'core/base.html' %}

{% block content %}
{% load static %}


{% include 'core/calendario.html' %}



{% if segmento_usuario != None %}
  {% include 'core/vistaSegmento.html' %}
{% endif %}

<div class="row my-5">
    <form method="GET" action="{% url 'home' %}" class="d-md-flex justify-content-around">
      <div class="col-md-3 col">
        <select class="form-select" name="segmento" onchange="this.form.submit()">
          <option value="Todos" 
                  {% if segmento_seleccionado == "Todos" %}
                  selected
                  {% endif %}>
                Segmentos
          </option>
          {% for segmento in segmentos %}
            {% if segmento.nombre != 'Developer' %}
              <option value="{{ segmento.nombre }}" 
                      {% if segmento_seleccionado == segmento.nombre %} 
                      selected 
                      {% endif %}>
                    {{ segmento.nombre }}
              </option>
            {% endif %}
          {% endfor %}
        </select>
      </div>
      <div class="col-md-3 col">
        <select class="form-select" name="tipo" onchange="this.form.submit()">
          <option value="Todos" 
                    {% if tipo_seleccionado == "Todos" %}
                    selected
                    {% endif %}>
                  Tipo
            </option>
            {% for tipo in tipos %}
              <option value="{{ tipo.0 }}" 
                      {% if tipo_seleccionado == tipo.0 %} 
                      selected 
                      {% endif %}>
                    {{ tipo.1 }}
              </option>
            {% endfor %} 
        </select>
      </div>
    </form>
</div>

<div class="row my-5 px-5" id="tabla">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Hito</th>
        <th scope="col">Fecha Inicio</th>
        <th scope="col">Fecha Término</th>
        <th scope="col">Tipo</th>
        <th scope="col">Segmento</th>
      </tr>
    </thead>
    <tbody>
      {% for evento in eventos %}
        <tr>
          <!--if evento.fechaInicio|date:"Y" == fecha_usuario|date:"Y" -->
            <td>{{ evento.titulo }}</td>
            <td>{{ evento.fechaInicio }}</td>
            <td>{{ evento.fechaTermino}}</td>
            <td>{{ evento.get_tipo_display }}</td>
            <td>
              {% for segmento in evento.segmento.all %}
                {{ segmento.nombre }}
                {% if not forloop.last %}-{% endif %}
              {% endfor %}
            </td>
          <!-- endif -->
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}

CER3/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block content %}
{% load static %}


<div class="d-flex justify-content-center align-items-center" style="height: 90vh;">
    <div class="card d-flex justify-content-center align-items-center" style="width: 18rem; background: #005f94;">
        <div class="card-body">
        <h5 class="card-title text-white">Login</h5>
            <p style="color: #D60019;">{{error}}</p>
            <form action="" method="POST" class="text-white">
            {% csrf_token %}
            {{form.as_p}}
            <button>Login</button>
            </form>
        </div>
    </div>
</div>


{% endblock %}

CER3/core/templates/core/vistaSegmento.html
<div class="container">
  <div class="row py-5">
    <div class="col">
      <h1>Próximos Eventos {{segmento_usuario}}</h1>
    </div>
  </div>
  
  <div class="row row-cols-1 row-cols-md-3 g-4">
    {% for evento in eventos_segmento %}
      <div class="col">
        <div class="card h-100">
          <div class="card-body">
            <h3 class="card-title">{{evento.fechaInicio|date:"d"}}</h3>
            <h4 class="card-title text-body-secondary">{{evento.fechaInicio|date:"F"}}</h4>
            <h6 class="card-text">{{evento.titulo}}</h6>
            <p class="card-text">{{evento.descripcion}}</p>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
</div>